# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepoKeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recourse',
            name='media_type',
            field=models.CharField(choices=[('AUDIO', 'audio'), ('TEXT', 'text'), ('VIDEO', 'video'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=100),
        ),
    ]
