# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 21:29
from __future__ import unicode_literals

import Portfile.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(upload_to=Portfile.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Masterpiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.FileField(upload_to=Portfile.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('register_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=Portfile.models.user_directory_path)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfile.User')),
            ],
        ),
        migrations.AddField(
            model_name='masterpiece',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfile.User'),
        ),
        migrations.AddField(
            model_name='image',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfile.User'),
        ),
    ]
