# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 19:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfile', '0002_auto_20160329_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='register_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Portfile.Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='key_expires',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
