# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfile', '0003_auto_20160330_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
